backend:
  name: git-gateway
  branch: Joseph-Updates
media_folder: 'public/assets/image'
public_folder: 'assets/artist'
collections:
  - name: 'artist'
    label: 'Artist'
    folder: 'src/artist'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Songs'
        name: 'songs'
        widget: 'list'
        fields:
          - { name: 'title', label: 'Title', widget: 'String' }
          - { name: 'artist', label: 'Artist', widget: 'string' }
          - { name: 'image', label: 'Image', widget: 'image' }
          - { name: 'tags', label: 'Tags', widget: 'list' }

  - name: 'post'
    label: 'Post'
    folder: 'src/blog/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Date Published', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Author Name', name: 'authorName', widget: 'string' }
      - { label: 'Author Image', name: 'authorImage', widget: 'image' }
      - {
          label: 'Author Description',
          name: 'authorDescription',
          widget: 'string',
        }
